# Generated by Django 6.0.6 on 2026-08-19 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_gender_created_at_alter_gender_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'male'), ('female', 'female'), ('unknown', 'unknown')], default='unknown', max_length=10, verbose_name='gender'),
        ),
        migrations.AddField(
            model_name='profile',
            name='gender_identity',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='gender identity'),
        ),
        migrations.AddField(
            model_name='profile',
            name='pronouns',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='pronouns'),
        ),
        migrations.AddField(
            model_name='profile',
            name='social_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='social name'),
        ),
        migrations.DeleteModel(
            name='Gender',
        ),
    ]
