# Generated by Django 6.0.6 on 2026-08-22 15:24

import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_profile_gender_profile_gender_identity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='document_type',
            field=models.CharField(blank=True, choices=[('cpf', 'CPF'), ('ssn', 'SSN'), ('passport', 'passport')], max_length=10, verbose_name='document type'),
        ),
        migrations.AddField(
            model_name='profile',
            name='nationality',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True, verbose_name='nationality'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='document',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='document'),
        ),
    ]
