# Generated by Django 6.0.5 on 2026-05-31 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='profile',
            new_name='idx_profile_document',
            old_name='accounts_pr_documen_e26cc9_idx',
        ),
        migrations.AlterField(
            model_name='profile',
            name='document',
            field=models.CharField(blank=True, max_length=11, null=True, unique=True),
        ),
    ]
